### ISSUE TITLE
BLE device tracker

### ISSUE THREAD

**Issue by Magalex2x14** [custom-components/ble_monitor#175]
Since our component works with a continuous stream of BLE messages, and as far as I know, the current solutions have problems and conflict with us, it naturally suggests itself add a tracker function to our component. In addition, users have repeatedly asked about this feature.

- [x] learn corresponding HA core API/helpers
- [x] setup "tracker platform"
- [x] get a list of tracked devices
- [x] in the HCIdump thread, catch the necessary mac addresses, and put them in a separate queue
- [x] in the code of the tracker module notify the HA core about detected devices
- [x] options (consider_home and others)

**Comment by Magalex2x14** [comment]
As far as I understood from the documentation, the `known_devices.yaml` file is out of date.
Looked at the GPSLogger code for an example - everything looks pretty simple.
Having a list of monitored devices, we update the corresponding entities when it detects packets from them.

To look further:

```python
from homeassistant.components.device_tracker import SOURCE_TYPE_GPS
from homeassistant.components.device_tracker.config_entry import TrackerEntity
SOURCE_TYPE_BLUETOOTH_LE = "bluetooth_le"
class ScannerEntity(BaseTrackerEntity):
```

**Comment by Magalex2x14** [comment]
Examples:

Legacy tracker: [bluetooth_le_tracker](https://github.com/home-assistant/core/blob/dev/homeassistant/components/bluetooth_le_tracker/device_tracker.py)
New tracker: [arpscan_tracker](https://github.com/cyberjunky/home-assistant-arpscan_tracker/blob/master/custom_components/arpscan_tracker/device_tracker.py)

**Comment by Magalex2x14** [comment]
Working tracker in `magalex_experiments` branch commit `legacy device tracker`
Populates the `known_devices.yaml` file with detected BLE devices with a public (not random) mac address.
I think it's worth making the `include` option mandatory so as not to overload the device list.

![image](https://user-images.githubusercontent.com/4982025/100664084-38f30c80-3368-11eb-95f4-c5df4979caa4.png)

**Comment by Magalex2x14** [comment]
works regardless of the `period` option, the name and other attributes can be changed in the `known_devices.yaml` file
the `interval_seconds` and `consider_home` options are processed by the HA core, the rest must be done by ourselves

**Comment by andrewjswan** [comment]
Is it possible to turn off the search for new devices when tracking is enabled?

**Comment by Magalex2x14** [comment]
As far as I understand:
- with the `track_new_devices: false` option, the `known_devices.yaml` file continues to populate with all discovered devices, but only entities with `track: true` are visible in HA
- the only way out that I see is to add a mandatory `include` or `track` option, in which the mac addresses of the tracked devices should be listed. Then it will be possible to transfer only what is needed to the HA core.

But I would not go into it now. We have to go to the UI configuration, so we need to figure out how to work with the UI configured tracker.

**Comment by andrewjswan** [comment]
In Router track integration if track_new_devices: false then no new devices in known_devices.yaml when true then new devices fall to known_devices.yaml and to HA

**Comment by andrewjswan** [comment]
And how about - consider_home - Seconds to wait till marking someone as not home after not being seen.

**Comment by Magalex2x14** [comment]
Judging by what I see in the source code in the HA repository: 
- the "new" tracker is essentially a platform that spawns the entities of the TrackerEntity class and updates them as the status is discovered/updated 
- the list of known devices and the list of tracked ones is completely on the shoulders of the platform 
- the track_new_devices option is at the discretion of the platform 
- the consider_home option, I suspect, is processed in the HA core, and the status of entities changes automatically based on the time of its last update (I did not find direct indications of this, it needs to be checked!) 

Thus, it turns out that we only need to create a new one (device_tracker) platform (quite similar to sensor or binary_sensor), which, in accordance with the period option, will parse its message queue and create / update entities of the TrackerEntity class.
Since from the bluetooth interface we receive a continuous stream of frequently repeated messages for each of the mac-addresses, we cannot do without filtering duplicates, and this should be done as early as possible, in the HCIdump thread, ~~and from the tracker platform, there must be access to the mechanism for resetting this filter (to clear the list of detected addresses at the end of each period).~~ Or clear this filter when restarting the scanner (despite the fact that the restart is initiated by the sensor platform, it does not matter).

We need to decide how we will configure the list of tracked devices.
So far I see two options: 
1. Add the track (True / False) option to the device-level settings. 
2. Add a separate tracked_devices option (by analogy with devices), which will be a list of mac addresses.

@Ernst79, what do you think is the best way to proceed?

**Comment by Ernst79** [comment]
I think the first option is the best and easiest. We already have settings on device level, which are not applicable for all devices (e.g. temperature setting is always in the UI, also for sensors that do not have temperature readings). So just add a track setting is fine. Perhaps ‘device tracker’ instead of ‘tracker’?

**Comment by andrewjswan** [comment]
IMHO better:
track: true
add_new_devices: false
consider_home: 60
tracked_devices:
- name: ...
  mac: ...
- name: ...
  mac: ...
- name: ...
  mac: ...

**Comment by Ernst79** [comment]
Thinking out of the box

ble_monitor
- sensor:
   discovery: True
   rounding: True
   ...
   devices:
   - mac: xxx
      name: yyy
- device tracker:
   add_new_devices: True
   consider_home: 60
   tracked_devices:
    - mac: xxx
       name: yyy

This means a breaking change however. You could even add binary_sensor: with different setting. e.g. the mean option isn’t relevant for binary sensors.

**Comment by Magalex2x14** [comment]
Yes, such a change suggests itself, but I don't really want to make another breaking change for now )
I suggest starting with a simple `track` per device, and then we'll see how it goes, and make a breaking change by thinking it thoroughly.

@andrewjswan

There is no point in making a separate `track: true` option. What will you track if the list of tracked devices is empty? It is worth relying only on the presence of tracked devices in the configuration, this option does not make sense. 

I will not do the `add_new_devices` option yet for several reasons:

- the `known_devices.yaml` is being phased out from 0.94, as indicated in the HA documentation. Therefore, our integration will work with entities, as I wrote above. 
- despite the fact that the range of bluetooth is limited, enabling such an option may in certain situations lead to a monstrous growth of this list and an increased "idle" load on the host.
- it is impossible to identify the device you need in the list of mac-addresses, you still have to specify the desired mac address from others sources (or know it in advance), which makes the existence of such a list meaningless. 

The `consider_home` option, as I understand it, is handled by the HA core (read the HA documentation for [Device Tracker](https://www.home-assistant.io/integrations/device_tracker/) integration). Anyway, this is how it works with trackers working with `known_devices.yaml`. I suspect it's the same for entities. I propose to make some tests first, nothing prevents us from implementing this option, if necessary. Until then, I see no reason to reinvent the wheel.

**Comment by Ernst79** [comment]
I can understand, not making breaking changes again. If we only limit ourselves to a `track` option only, we can keep it as your first option, I agree. If we end up with a lot of settings specifically for device_trackers, we might need to reconsider.

Isn't the `add_new_devices` already covered by the `discovery` option (sort of)?

**Comment by Magalex2x14** [comment]
> Isn't the add_new_devices already covered by the discovery option (sort of)?
Yes, but discovery option is limited to supported sensors for now, and since the device tracker works with mac-addresses only (regardless of device type), all bluetooth le devices within the range of reception will be included in the list of detected devices (spawned entities), which entails a lot of problems.

**Comment by Ernst79** [comment]
Agreed, that makes sense.

**Comment by andrewjswan** [comment]
@Magalex2x14 How are you?

**Comment by vevsvevs** [comment]
@Ernst79 @Magalex2x14, eagerly waiting for this too ;)

**Comment by vevsvevs** [comment]
Please do not drop this off! Personally, I'd definitely prefer to go off the ESPHome tracker solution to this all-in-one solution.

**Comment by Magalex2x14** [comment]
Hi, @vevsvevs. I remember this task, and it will be the first thing I will undertake when there is free time... Unless @Ernst79 wants to do it himself sooner.

**Comment by Ernst79** [comment]
I had just started reading how this device tracking works, I will try to make a start soon. Not sure when I will finish though, still learning. All other major tasks have more or less been completed, so I can spend some time on this.

**Comment by Ernst79** [comment]
A quick update. I'm more or less finished with the device tracker implementation. Seems to be working fine.  

![image](https://user-images.githubusercontent.com/24375847/124188659-d9a4d880-dabf-11eb-9fa3-4802f859bc43.png)

I have to do some cleaning of the code, but I hope to finish things this weekend for a first draft. 

One thing I have to do is perhaps limiting the amount of state updates, it is now updating on each BLE message. I think it would be good/better to catch the first message, but after that, wait e.g. x seconds before the next update.

**Comment by vevsvevs** [comment]
@Ernst79 such a wonderful news! Regarding update frequency: maybe it's a good idea to make an integration option with polling interval value for each MAC set in tracker?

**Comment by Ernst79** [comment]
Yes, I think we will need something like that. As an example, I used one of my sensors as device tracker. This thing will send a message every 3 seconds, causing an update of the state and RSSI every 3 seconds. I don't think that will be needed and will only spam the HA instance. 

Somewhat related, I'm not sure how HA will deal with the "not home" status, and how we should relate this to the polling interval (actually, it isn't polling, it is receiving the data anyway, as it is just listening). 

For the current version, I had added an option `track_device` under devices. So, in YAML, this would look like

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
  period: 60
  devices:
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'beacon 1'
      track_device: True
```

We could use the `reset_timer` to tell BLE monitor when we should consider the device not home. But I have to figure out what HA is doing on its own (at least, I think it will go to Not Home after a while, not tested yet). 

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
  period: 60
  devices:
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'beacon 1'
      track_device: True
      reset_timer: 30
```

Adding a update interval will result in

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
  period: 60
  devices:
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'beacon 1'
      track_device: True
      reset_timer: 60
      update_interval: 20
```

Another thing to choose is do we split up devices into `devices` and `tracker_devices` or not? It is not needed to split it up, as it will populate a list with trackers based on the `track_device` setting of each device. On the other hand, in the UI configuration, the device options will show all options that can be set for a device, so also temperature unit, etc. 

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
  period: 60
  devices:
    - mac: 'A4:C1:38:2F:86:6B'
      name: 'Livingroom'
      encryption_key: '217C568CF5D22808DA20181502D84C1B'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'beacon 1'
      track_device: True
      reset_timer: 60
      update_interval: 20
```

or

```
ble_monitor:
  bt_interface: '04:B1:38:2C:84:2B'
  period: 60
  devices:
    - mac: 'A4:C1:38:2F:86:6C'
      name: 'Livingroom'
      encryption_key: '217C568CF5D22808DA20181502D84C1B'
      temperature_unit: C
      decimals: 2
      use_median: False
      restore_state: default
  tracker_devices:
    - mac: 'A4:C1:38:2F:86:6B'
      name: 'beacon 1'
      track_device: True
      reset_timer: 60
      update_interval: 20
```

For now, I have a slight preference for the first option, but I would like to know your opinion

**Comment by Ernst79** [comment]
Added a last seen attribute to be able to use the `reset_timer`

![image](https://user-images.githubusercontent.com/24375847/124321250-ac1e6480-db7d-11eb-832b-8fc31b0acaa7.png)

**Comment by vevsvevs** [comment]
It will take some time for me to get into stuff you mentioned, as I know nothing about HA's person/device tracking implementation :) But as a side note: maybe mutually exclusive options like "State change tracking" (meaning completely ignoring RSSI and other attributes) and "Polling interval" will be enough? The first option will fit those who want to only track presence/absence (like me), whereas the second one will fit the continuously RSSI-based proximity tracking task (at the cost of chosen data update frequency).

**Comment by Ernst79** [comment]
I had a bit of trouble with getting the state back to `Away`, but I finally managed to get it working. 

![image](https://user-images.githubusercontent.com/24375847/124392972-88335e00-dcf8-11eb-8ab7-f550d5151024.png)

The options I have now

![image](https://user-images.githubusercontent.com/24375847/124393009-adc06780-dcf8-11eb-953e-f877256a0020.png)

I'm going to do some testing tonight, hopefully a beta tomorrow

**Comment by Ernst79** [comment]
3.6.0-beta has been released, with the following release notes. Please give it a try and let me know if you find any issue. 

## Changes in 3.6.0-beta

This PR adds support for **device trackers**!!! You can now track every Bluetooth device with BLE monitor. 

To enable tracking of a device, add the Bluetooth MAC address to your `devices` in the options menu and enable the option `track device`.

Still using YAML?, you can add your device tracker with the following config:

```YAML
ble_monitor:
  devices:
    - mac: 'D4:3C:2D:4A:3C:D5'
      track_device: True
      tracker_scan_interval: 20
      consider_home: 180
```

This PR also adds support for the Dutch language

**Comment by Ernst79** [comment]
@vevsvevs Did you give it a try? Can you tell me if everything is working as expected?

**Comment by vevsvevs** [comment]
@Ernst79 sorry for the delay, got some affairs on my own project... I will check it and report asap. Many thanks for your efforts put into it!

**Comment by vevsvevs** [comment]
So, it looks like tracking works well! But the encrypted sensors stopped to work :) Not sure whether it's a component issue or HA itself, because I've updated to 2021.7.0 same turn (stupid me). Now, among the mass other errors i have these two caused by the component: https://hastebin.com/oburaragor.apache

**Comment by Ernst79** [comment]
Ah, I have a clue what is wrong, I forgot to make an exception for macs that do not have a sensortype, like devices you want to track that aren’t sensors as well. I’ll fix it tomorrow, please remove the Mac of the device tracker for now

**Comment by Ernst79** [comment]
3.7.2-beta has been released which should fix the issue. Could you give it another try and report back your findings.

**Comment by vevsvevs** [comment]
Now all is working well, thanks again! I will switch to this type of tracking and report if there some issues in the future.

**Comment by Ernst79** [comment]
4.0.0 has been released with final support for device tracking

**Comment by vevsvevs** [comment]
@Ernst79 you're awesome! Thank you for this feature!
